name: 'run BiliExp'

on:
  schedule:
    - cron: '*/10 0-17 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: BiliExp-Actions

    - name: 安装依赖库
      run: |
          sudo -H pip3 install --upgrade setuptools
          sudo -H pip3 install -r requirements.txt
    - name: 配置用户信息
      run: python3 secrets2config.py
      env:
          ADVCONFIG: ${{ secrets.ADVCONFIG }}
          BILICONFIG: ${{ secrets.BILICONFIG }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}

    - name: 执行BiliExp.py
      run: python3 BiliExp.py
